source ~/.vim/myBundle.vim
syntax enable
set number
set relativenumber
set nowrap

" Split line (works with delimitMate)
imap <C-c> <CR><Esc>O

" Use tabs by default
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Use specific spacing for different formats
autocmd BufNewFile,BufRead *.v   setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4
autocmd BufNewFile,BufRead *.lua setlocal expandtab tabstop=3 shiftwidth=3 softtabstop=3
autocmd BufNewFile,BufRead *.c   setlocal expandtab tabstop=4 shiftwidth=2 softtabstop=2
autocmd BufNewFile,BufRead *.m   setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

" Status bar formatting
set laststatus=2
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

" molokai settings """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
colorscheme molokai
hi diffAdded   ctermbg=NONE ctermfg=10 cterm=NONE guibg=NONE guifg=#B9FC32 gui=NONE
hi diffRemoved ctermbg=NONE ctermfg=9  cterm=NONE guibg=NONE guifg=#FF2676 gui=NONE
hi link diffLine String
hi link diffSubname Normal
set colorcolumn=81
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Show tabs and trailing spaces.
set encoding=utf-8
set list listchars=tab:▸\ ,trail:·

" Unrecogised extensions fix
au BufRead,BufNewFile *.rockspec set filetype=lua
au BufRead,BufNewFile *.md       set filetype=markdown

" Ask to clean all trailing white-spaces upon saving
autocmd BufWritePre * :%s/\s\+$//ec

" Set HighLight Search by default. :noh for toggling
set hls

" Wildmenu
set wildmenu

" Automatically switch between syntax and manual foldmethod
autocmd BufNewFile,BufRead *.{java,c} setlocal foldmethod=syntax foldcolumn=4
autocmd InsertLeave,WinEnter *.{java,c,bib} setlocal foldmethod=syntax
autocmd InsertEnter,WinLeave *.{java,c,bib} setlocal foldmethod=manual

" TeX settings
autocmd BufNewFile,BufRead *.{tex,bib} setlocal colorcolumn=0 norelativenumber wrap autowrite

" C-Return to send below
let delimitMate_expand_cr=1
